# Listar todos los carritos
GET http://localhost:8083/carrito
###

# Obtener un carrito específico por ID
GET http://localhost:8083/carrito/1
###

# Crear un nuevo carrito
POST http://localhost:8083/carrito
Content-Type: application/json

{
  "precioTotal": 120.50,
  "servicios": [1, 2, 3],
  "idCliente": 1
}

###

# Eliminar un carrito por ID
DELETE http://localhost:8083/carrito/1

###

# Actualizar un carrito por ID
PUT http://localhost:8083/carrito/1
Content-Type: application/json

{
  "precioTotal": 150.75,
  "servicios": [2, 3, 4],
  "idCliente": 2
}
